### ISSUE TITLE
Missing URL

### ISSUE THREAD

**Issue by inferiore** [osteel/openapi-httpfoundation-testing-laravel-example#1]
Hey! Body 
I was looking at your Doc to implement this  package in my Laravel Project, Suddenly I realised that your documentation is point to pages that aren't found, could you fixed? 
# Missing URL
![image](https://user-images.githubusercontent.com/4751556/153900391-52bbc371-be7d-4aa7-8a29-48d668293143.png)

Thanks

**Comment by osteel** [comment]
Good catch! Should be fixed
